/**
 * Lifts device instances out of the donor racks and writes them into the codec
 * as XML strings.
 *
 * Device XML cannot be generated, only copied (doc/DEVELOPERS.md, Constraint 7): a
 * stock Live device is hundreds of facts and one assembled from a description
 * produces a file that loads without complaint and behaves wrong. So the
 * contract inserts a real instance, saved by Live, harvested from
 * `packages/adg-codec/donors/*.adg`.
 *
 * Harvesting at build time rather than reading the `.adg` at runtime keeps the
 * codec free of file access and gzip work it would otherwise need in a browser
 * tab.
 *
 *     pnpm adg-harvest
 */
import { gunzipSync } from 'node:zlib';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';

// Same global shim as index.ts: the codec and these helpers expect a
// browser-shaped DOMParser/XMLSerializer.
const { window } = new JSDOM();
const parser = new window.DOMParser();
const serializer = new window.XMLSerializer();

const DONORS = join(process.cwd(), 'packages', 'adg-codec', 'donors');
const OUT = join(process.cwd(), 'packages', 'adg-codec', 'src', 'donorLibrary.generated.ts');

/** Device tags the contract can insert. Growing this list means saving the device into a donor rack first. */
const WANTED = ['StereoGain', 'Gate', 'Compressor2', 'AutoFilter2', 'FilterEQ3'];

/**
 * Dropped from a harvested device. A donor is wanted for its parameter list
 * and each parameter's native range, never for anybody's settings, and three
 * of these actively break an inserted copy:
 *
 * - `KeyMidi` is a macro mapping. The Utility in every donor here is already
 *   bound to that rack's gain macro, and carrying it over would bind the
 *   inserted device to whatever macro index the donor happened to use.
 * - `SourceContext` and `LastPresetRef` can hold paths into the machine the
 *   donor was saved on.
 */
const STRIP_TAGS = ['KeyMidi', 'SourceContext', 'LastPresetRef'];

/** Blanked rather than removed: Live writes them on every device and their absence is a shape change. */
const BLANK_TAGS = ['UserName', 'Annotation'];

function elements(node: Element, tag: string): Element[] {
  return Array.from(node.getElementsByTagName(tag)) as unknown as Element[];
}

/** The device tag an `AbletonDevicePreset` wraps, or null if it wraps nothing recognisable. */
function deviceTagOf(preset: Element): string | null {
  const device = Array.from(preset.childNodes).find(
    (n) => (n as Element).nodeType === 1 && (n as Element).tagName === 'Device',
  ) as Element | undefined;
  const inner = device && (Array.from(device.childNodes).find((n) => (n as Element).nodeType === 1) as Element | undefined);
  return inner?.tagName ?? null;
}

function scrub(preset: Element): void {
  for (const tag of STRIP_TAGS) {
    for (const el of elements(preset, tag)) el.parentNode?.removeChild(el);
  }
  for (const tag of BLANK_TAGS) {
    for (const el of elements(preset, tag)) el.setAttribute('Value', '');
  }
  // Ids are reallocated on insert (doc/DEVELOPERS.md, the contract). Zeroing them here means
  // a donor that leaked into a file unrenumbered is obvious rather than subtly
  // colliding with a real one.
  const walk = (el: Element) => {
    if (el.hasAttribute?.('Id')) el.setAttribute('Id', '0');
    for (const c of Array.from(el.childNodes)) {
      if ((c as Element).nodeType === 1) walk(c as Element);
    }
  };
  walk(preset);
}

function main(): void {
  const found = new Map<string, { xml: string; source: string }>();

  for (const file of readdirSync(DONORS).filter((f) => f.endsWith('.adg')).sort()) {
    const xml = gunzipSync(readFileSync(join(DONORS, file))).toString('utf8');
    const doc = parser.parseFromString(xml, 'text/xml');
    for (const preset of elements(doc.documentElement as unknown as Element, 'AbletonDevicePreset')) {
      const tag = deviceTagOf(preset);
      if (!tag || !WANTED.includes(tag) || found.has(tag)) continue;
      const copy = preset.cloneNode(true) as unknown as Element;
      scrub(copy);
      found.set(tag, { xml: serializer.serializeToString(copy as never), source: file });
    }
  }

  const missing = WANTED.filter((t) => !found.has(t));
  const entries = [...found.entries()].sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(([tag, { xml, source }]) => `  // from donors/${source}\n  ${tag}: ${JSON.stringify(xml)},`)
    .join('\n');

  writeFileSync(
    OUT,
    `// GENERATED by \`pnpm adg-harvest\` from packages/adg-codec/donors/*.adg.
// Do not edit. To add a device, save it into a donor rack and re-run.
//
// Each entry is one \`AbletonDevicePreset\`, scrubbed of macro bindings, names,
// annotations and machine paths, with every Id zeroed for reallocation on
// insert (doc/DEVELOPERS.md, Constraint 7, 4.3.4).

export const DONOR_DEVICES: Readonly<Record<string, string>> = {
${body}
};

/** Device tags the contract can insert today. */
export type DonorDeviceTag = keyof typeof DONOR_DEVICES;
`,
    'utf8',
  );

  for (const [tag, { source, xml }] of entries) {
    console.log(`${tag.padEnd(16)} ${String(xml.length).padStart(7)} bytes  from ${source}`);
  }
  if (missing.length > 0) {
    console.log(`\nNOT FOUND in any donor: ${missing.join(', ')}`);
    console.log('Save the device into a rack, drop it in packages/adg-codec/donors/, and re-run.');
  }
  console.log(`\nwrote ${OUT}`);
}

main();
